### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by DrkMatr1984** [Qveshn/ShinyItems#1]
So I've been trying to compile the project from source. Everything works except for in the pom.xml you have
 
`<dependency>
            <groupId>ru.beykerykt</groupId>
            <artifactId>lightapi</artifactId>
            <version>5.0.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/LightAPI-Bukkit-5.0.0.jar</systemPath>
</dependency>`

Which is unresolved. I built beykerykt's light api 5.0.0 from source and got the correct bukkit jar, however, he has changed the internal structure of the API and in LightAPIv5.java inside ShinyItems, these two imports are no longer found inside the new jar. 

`import ru.beykerykt.minecraft.lightapi.common.IChunkData;
import ru.beykerykt.minecraft.lightapi.common.LightType;`

I'm unsure where or how to replace the methods inside LightAPIv5.java 's  code to match up with the newer LightAPI from beykerykt. Spigot uses your version of v3 currently, so I could just delete the v5 references inside ShinyItems and maintain in strictly as a bukkit plugin for myself, but I wanted to see if perhaps you had the old jar for v5 so I could compile cleanly or if you had a more elegant solution before I butcher some code :P 

Thanks for your time!

**Comment by Qveshn** [comment]
Hi
https://github.com/Qveshn/ShinyItems/tree/master/lib
You can find binary jar file 5.0.0 there. It is the same as 3.2.8. Look the note below the first table.
Here is download link: https://www.spigotmc.org/resources/lightapi.4510/download?version=273691

If you need LightAPI 5.0.0 just to compile, but will use LightAPI fork, then just download as I told above and save it to "lib" folder as "LightAPI-Bukkit-5.0.0.jar"

Notes: "LightAPI" and "LightAPI fork" - they are two different branches. You should use only one of them with your server.
If you want to use "LightAPI fork" then download 3.5.2 instead 3.4.2 here https://www.spigotmc.org/resources/lightapi-fork.48247/

**Comment by DrkMatr1984** [comment]
Gotcha. Yeah I had already figured that part out with the forks, just couldn't find the lib to compile. I am actually using the fork on my server currently, and it works great! Thanks for all your hard work and thanks for taking the time to point me in the right direction :p
